export const defaults = {
  minAge: 0,
  maxAge: 100,
  minYear: null,
  maxYear: 'now',
  lowerLimit: null,
  upperLimit: null,
  monthFormat: 'short',
  placeholder: true,
  className: null,
  defaultDate: null,
  autoInit: true,
  leadingZero: true,
  locale: 'en',
  selectFuture: false,
  arrange: 'ymd',
  yearEl: null,
  monthEl: null,
  dayEl: null,
  roundDownDay: true,
};
